---
title: Kit Meng —— Digital Art Director
timezone: Asia/Kuala_Lumpur
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Work
    output: true
site:
  description: www.kitmeng.com | I create digital experiences for the Web.
baseurl: 
url: http://kitmeng.com
markdown: kramdown
paginate: 20
paginate_path: "/page/:num/"
plugins:
- jekyll-paginate
- jekyll-seo-tag
- neat
highlighter: rouge
